export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Entertainment } from "./Entertainment";
export { default as Support } from "./Support";
export { default as Phones } from "./Phones";
export { default as SmartHome } from "./SmartHome";
export { default as Register } from "./Register";
export { default as SignIn } from "./SignIn";
export { default as NotFound } from "./NotFound";
export { default as ErrorPage } from "./ErrorPage";
export { default as ShoppingCart } from "./ShoppingCart";
export { Category } from "./Category";
